//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace categoryIndex {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Projem.WebUI.App_LocalResources.Category.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        public static string anasayfa {
            get {
                return ResourceManager.GetString("anasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tr.
        /// </summary>
        public static string dil {
            get {
                return ResourceManager.GetString("dil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrele.
        /// </summary>
        public static string filtrele {
            get {
                return ResourceManager.GetString("filtrele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtreleme.
        /// </summary>
        public static string filtreleme {
            get {
                return ResourceManager.GetString("filtreleme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiyat.
        /// </summary>
        public static string fiyat {
            get {
                return ResourceManager.GetString("fiyat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İndirim.
        /// </summary>
        public static string indirim {
            get {
                return ResourceManager.GetString("indirim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoriler.
        /// </summary>
        public static string kategoriler {
            get {
                return ResourceManager.GetString("kategoriler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoriler.
        /// </summary>
        public static string kategoriler2 {
            get {
                return ResourceManager.GetString("kategoriler2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Sayfası.
        /// </summary>
        public static string kategorisayfası {
            get {
                return ResourceManager.GetString("kategorisayfası", resourceCulture);
            }
        }
    }
}
