//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace productDil {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Detail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Detail() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Projem.WebUI.App_LocalResources.Product.Detail", typeof(Detail).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        public static string anasayfa {
            get {
                return ResourceManager.GetString("anasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bakım Detayları.
        /// </summary>
        public static string bakimdetaylari {
            get {
                return ResourceManager.GetString("bakimdetaylari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgi.
        /// </summary>
        public static string bilgi {
            get {
                return ResourceManager.GetString("bilgi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tr.
        /// </summary>
        public static string dil {
            get {
                return ResourceManager.GetString("dil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eve Teslim.
        /// </summary>
        public static string eveteslim {
            get {
                return ResourceManager.GetString("eveteslim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-4 Gün.
        /// </summary>
        public static string gun {
            get {
                return ResourceManager.GetString("gun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 Günde İade.
        /// </summary>
        public static string iade {
            get {
                return ResourceManager.GetString("iade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlgili Ürünler.
        /// </summary>
        public static string ilgiliurunler {
            get {
                return ResourceManager.GetString("ilgiliurunler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapıda Ödeme.
        /// </summary>
        public static string kapidaodeme {
            get {
                return ResourceManager.GetString("kapidaodeme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mevcut.
        /// </summary>
        public static string mevcut {
            get {
                return ResourceManager.GetString("mevcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miktar.
        /// </summary>
        public static string miktar {
            get {
                return ResourceManager.GetString("miktar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nakliye ve İade.
        /// </summary>
        public static string nakliyeveiade {
            get {
                return ResourceManager.GetString("nakliyeveiade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepete Ekle.
        /// </summary>
        public static string sepeteekle {
            get {
                return ResourceManager.GetString("sepeteekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şimdi Satın Al.
        /// </summary>
        public static string simdisatinal {
            get {
                return ResourceManager.GetString("simdisatinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stokta Var.
        /// </summary>
        public static string stoktavar {
            get {
                return ResourceManager.GetString("stoktavar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tükendi.
        /// </summary>
        public static string tukendi {
            get {
                return ResourceManager.GetString("tukendi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Ürünler.
        /// </summary>
        public static string tumurunler {
            get {
                return ResourceManager.GetString("tumurunler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Detayı.
        /// </summary>
        public static string urundetayi {
            get {
                return ResourceManager.GetString("urundetayi", resourceCulture);
            }
        }
    }
}
