//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dil {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Footer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Footer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Projem.WebUI.App_LocalResources.Home.Footer", typeof(Footer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basın.
        /// </summary>
        public static string basin {
            get {
                return ResourceManager.GetString("basin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BİZE ULAŞIN.
        /// </summary>
        public static string bizeulasin {
            get {
                return ResourceManager.GetString("bizeulasin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string blog {
            get {
                return ResourceManager.GetString("blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloggerlar.
        /// </summary>
        public static string bloggerlar {
            get {
                return ResourceManager.GetString("bloggerlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BU YILIN TRENDLERİ.
        /// </summary>
        public static string buyilintrendleri {
            get {
                return ResourceManager.GetString("buyilintrendleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daha Fazlası....
        /// </summary>
        public static string dahafazlasi {
            get {
                return ResourceManager.GetString("dahafazlasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destek.
        /// </summary>
        public static string destek {
            get {
                return ResourceManager.GetString("destek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tr.
        /// </summary>
        public static string dil {
            get {
                return ResourceManager.GetString("dil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımızda.
        /// </summary>
        public static string hakkimizda {
            get {
                return ResourceManager.GetString("hakkimizda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAKKIMIZDA.
        /// </summary>
        public static string hakkimizda2 {
            get {
                return ResourceManager.GetString("hakkimizda2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIZLI ERİŞİM.
        /// </summary>
        public static string hizlierisim {
            get {
                return ResourceManager.GetString("hizlierisim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İade.
        /// </summary>
        public static string iade {
            get {
                return ResourceManager.GetString("iade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kargo.
        /// </summary>
        public static string kargo {
            get {
                return ResourceManager.GetString("kargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanım Şartları.
        /// </summary>
        public static string kullanimsartlari {
            get {
                return ResourceManager.GetString("kullanimsartlari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partnerler.
        /// </summary>
        public static string ortaklar {
            get {
                return ResourceManager.GetString("ortaklar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipariş Takibi.
        /// </summary>
        public static string siparistakibi {
            get {
                return ResourceManager.GetString("siparistakibi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIKÇA SORULAN SORULAR.
        /// </summary>
        public static string sssorular {
            get {
                return ResourceManager.GetString("sssorular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasarım Çiçekler.
        /// </summary>
        public static string tasarimcicekler {
            get {
                return ResourceManager.GetString("tasarimcicekler", resourceCulture);
            }
        }
    }
}
