//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dil {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Header {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Header() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Projem.WebUI.App_LocalResources.Home.Header", typeof(Header).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alışveriş Onay Sayfası.
        /// </summary>
        public static string alisverisonaysayfası {
            get {
                return ResourceManager.GetString("alisverisonaysayfası", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alışveriş Sepetim.
        /// </summary>
        public static string alisverissepetim {
            get {
                return ResourceManager.GetString("alisverissepetim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        public static string anasayfa {
            get {
                return ResourceManager.GetString("anasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ara.
        /// </summary>
        public static string arama {
            get {
                return ResourceManager.GetString("arama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string blog {
            get {
                return ResourceManager.GetString("blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tr.
        /// </summary>
        public static string dil {
            get {
                return ResourceManager.GetString("dil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        public static string girisyap {
            get {
                return ResourceManager.GetString("girisyap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim Sayfası.
        /// </summary>
        public static string iletisimsayfası {
            get {
                return ResourceManager.GetString("iletisimsayfası", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Sayfası.
        /// </summary>
        public static string kategorisayfası {
            get {
                return ResourceManager.GetString("kategorisayfası", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfalar.
        /// </summary>
        public static string sayfalar {
            get {
                return ResourceManager.GetString("sayfalar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepet.
        /// </summary>
        public static string sepet {
            get {
                return ResourceManager.GetString("sepet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Üyelik.
        /// </summary>
        public static string yeniuyelik {
            get {
                return ResourceManager.GetString("yeniuyelik", resourceCulture);
            }
        }
    }
}
