//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dil {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Projem.WebUI.App_LocalResources.Home.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tr.
        /// </summary>
        public static string dil {
            get {
                return ResourceManager.GetString("dil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EN ÇOK SATILAN ÜRÜNLER.
        /// </summary>
        public static string encoksatilanurunler {
            get {
                return ResourceManager.GetString("encoksatilanurunler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EN YENİ ÜRÜNLER.
        /// </summary>
        public static string enyeniurunler {
            get {
                return ResourceManager.GetString("enyeniurunler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EN ŞIK ÜRÜNLER.
        /// </summary>
        public static string esurunler {
            get {
                return ResourceManager.GetString("esurunler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIZLI ÖDEME SEÇENEKLERİ.
        /// </summary>
        public static string hizliodeme {
            get {
                return ResourceManager.GetString("hizliodeme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İNDİRİM.
        /// </summary>
        public static string indirim {
            get {
                return ResourceManager.GetString("indirim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KEŞFET.
        /// </summary>
        public static string kesfet {
            get {
                return ResourceManager.GetString("kesfet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEPET.
        /// </summary>
        public static string sepet {
            get {
                return ResourceManager.GetString("sepet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ŞİMDİ AL.
        /// </summary>
        public static string simdial {
            get {
                return ResourceManager.GetString("simdial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÜCRETSİZ VE HIZLI KARGO.
        /// </summary>
        public static string ucretsizhizlikargo {
            get {
                return ResourceManager.GetString("ucretsizhizlikargo", resourceCulture);
            }
        }
    }
}
