//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cartIndex {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Projem.WebUI.App_LocalResources.Cart.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alışverişe Devam Et.
        /// </summary>
        public static string alisverisedevamet {
            get {
                return ResourceManager.GetString("alisverisedevamet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alışverişe Devam Et.
        /// </summary>
        public static string alisverisedevamet2 {
            get {
                return ResourceManager.GetString("alisverisedevamet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alışverişi Tamamla.
        /// </summary>
        public static string alisverisitamamla {
            get {
                return ResourceManager.GetString("alisverisitamamla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALIŞVERİŞ SEPETİM.
        /// </summary>
        public static string alisverissepetim {
            get {
                return ResourceManager.GetString("alisverissepetim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alışveriş Sepetim.
        /// </summary>
        public static string alisverissepetim2 {
            get {
                return ResourceManager.GetString("alisverissepetim2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alışveriş Sepetim.
        /// </summary>
        public static string alisverissepetim3 {
            get {
                return ResourceManager.GetString("alisverissepetim3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        public static string anasayfa {
            get {
                return ResourceManager.GetString("anasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tr.
        /// </summary>
        public static string dil {
            get {
                return ResourceManager.GetString("dil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiyat.
        /// </summary>
        public static string fiyat {
            get {
                return ResourceManager.GetString("fiyat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miktar.
        /// </summary>
        public static string miktar {
            get {
                return ResourceManager.GetString("miktar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepete Ekle.
        /// </summary>
        public static string sepeteekle {
            get {
                return ResourceManager.GetString("sepeteekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOPLAM.
        /// </summary>
        public static string toplam {
            get {
                return ResourceManager.GetString("toplam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Adı.
        /// </summary>
        public static string urunadi {
            get {
                return ResourceManager.GetString("urunadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YENİ.
        /// </summary>
        public static string yeni {
            get {
                return ResourceManager.GetString("yeni", resourceCulture);
            }
        }
    }
}
